# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8cdc965d98a35ed6c2b56b81efd5c80d81b66d50515901fa10dba66b877b4bdadfb3de40da50dce4b39094da19bc7fbfe29556dfdf28281b81b2cb34be63b4b

test:
  secret_key_base: b71b4f9607128bfc7424e813a3c250a8412bc6b9a388b7fb0093a3d6eb1407a57756349dc6079e641cb4165175b8ded1eaaf701eb7a927304547e79ee5df8634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
